import streamlit as st
import time

# Page configuration
st.set_page_config(
    page_title="Medical Diagnostic Assistant",
    page_icon="🏥",
    layout="wide"
)

# Custom CSS for styling
st.markdown("""
    <style>
    .block-container {
        padding-top: 3rem !important; 
        padding-bottom: 2rem !important;
    }
    .greeting {
        font-size: 4rem !important;
        color: #1f77b4;
        font-weight: 800;
        margin-bottom: 0px;
        line-height: 1.2;
    }
    .sub-greeting {
        font-size: 1.8rem !important;
        color: #4a4a4a;
        font-weight: 300;
        margin-top: 0px;
        margin-bottom: 3rem;
    }
    .disclaimer-box {
        margin-top: 3rem;
        padding: 1rem;
        background-color: #fff3cd;
        border: 1px solid #ffeeba;
        color: #856404;
        border-radius: 0.25rem;
        font-size: 0.9rem;
        text-align: center;
    }
    </style>
""", unsafe_allow_html=True)

# --- Header Section ---
st.markdown('<div class="greeting">Hello, Doctor 👋</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-greeting">Let\'s get started.</div>', unsafe_allow_html=True)

# --- Step 1: Ambient AI Audio Input ---
st.write("### 1. Consultation Audio")
audio_file = st.file_uploader(
    "Upload Audio (Optional if Patient History is provided)", 
    type=['mp3', 'wav', 'm4a']
)

if audio_file:
    st.success(f"Audio loaded: {audio_file.name}")

st.markdown("---")

# --- Step 2: Medical Files Input ---
st.write("### 2. Patient History")
add_medical_file = st.radio(
    "Do you want to add a Medical file for this patient?", 
    ('No', 'Yes'),
    horizontal=True
)

uploaded_files = []

if add_medical_file == 'Yes':
    st.info("You can upload a single PDF or multiple image pages.")
    uploaded_files = st.file_uploader(
        "Upload Patient Records (PDF or Images)", 
        type=['pdf', 'png', 'jpg', 'jpeg'], 
        accept_multiple_files=True
    )
    
    if uploaded_files:
        st.write(f"**{len(uploaded_files)} file(s) attached.**")
        for file in uploaded_files:
            st.caption(f"📄 {file.name}")

st.markdown("---")

# --- Step 3: Submission Logic ---
if st.button("🚀 Submit & Generate Diagnosis", type="primary", use_container_width=False):
    
    # Check what inputs we have
    has_audio = audio_file is not None
    has_files = add_medical_file == 'Yes' and bool(uploaded_files)

    # LOGIC: If NEITHER is present, stop.
    if not has_audio and not has_files:
        st.error("⚠️ Please provide at least one input: Audio Recording OR Patient Files.")
    
    else:
        # Create status container
        status_container = st.status("Initializing AI System...", expanded=True)
        
        with status_container:
            # 1. Process Audio (Only if present)
            if has_audio:
                st.write("🎙️ **Transcribing Audio...**")
                time.sleep(1.5) 
                st.write("✅ Transcription Complete.")
            else:
                st.write("ℹ️ No audio provided. Skipping transcription.")

            # 2. Process Files (Only if present)
            if has_files:
                st.write("📂 **Reading Patient Files...**")
                time.sleep(1.5)
                st.write("✅ Medical History Extracted.")
            else:
                st.write("ℹ️ No files provided. Skipping record analysis.")

            # 3. Final Diagnosis
            st.write("🧠 **Synthesizing Data & Creating Diagnosis...**")
            time.sleep(1.5)
            
            status_container.update(label="Analysis Complete!", state="complete", expanded=False)

        # Show Success
        st.success("🎉 Diagnosis Generated Successfully!")
        
        st.markdown("### 📋 Assessment Summary")
        if has_audio and not has_files:
            st.info("Generated based on Consultation Audio only.")
        elif has_files and not has_audio:
            st.info("Generated based on Patient Records only.")
        else:
            st.info("Generated by combining Audio insights + Patient Records.")

# --- Disclaimer ---
st.markdown("""
<div class="disclaimer-box">
    <strong>⚠️ DISCLAIMER: AI-Assisted Diagnosis</strong><br>
    This diagnosis is generated by Artificial Intelligence and is subject to potential inaccuracies. 
    It is designed to function <strong>solely as a decision support tool</strong>. 
    It does not replace professional medical judgment. 
</div>
""", unsafe_allow_html=True)
