import streamlit as st
import time

# Page configuration
st.set_page_config(
    page_title="Medical Diagnostic Assistant",
    page_icon="🏥",
    layout="wide"
)

# Custom CSS for styling and layout fixes
st.markdown("""
    <style>
    /* 1. Fix the top padding so the header doesn't cover the text */
    .block-container {
        padding-top: 3rem !important; 
        padding-bottom: 2rem !important;
    }
    
    /* 2. Make the greeting much bigger */
    .greeting {
        font-size: 4rem !important;
        color: #1f77b4;
        font-weight: 800;
        margin-bottom: 0px;
        line-height: 1.2;
    }
    
    /* 3. Style the sub-greeting */
    .sub-greeting {
        font-size: 1.8rem !important;
        color: #4a4a4a;
        font-weight: 300;
        margin-top: 0px;
        margin-bottom: 3rem;
    }
    
    /* 4. Disclaimer specific styling */
    .disclaimer-box {
        margin-top: 3rem;
        padding: 1rem;
        background-color: #fff3cd;
        border: 1px solid #ffeeba;
        color: #856404;
        border-radius: 0.25rem;
        font-size: 0.9rem;
        text-align: center;
    }
    </style>
""", unsafe_allow_html=True)

# --- Header Section (Top Left) ---
st.markdown('<div class="greeting">Hello, Doctor 👋</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-greeting">Let\'s get started.</div>', unsafe_allow_html=True)

# --- Step 1: Ambient AI Audio Input ---
st.write("### 1. Consultation Audio")
audio_file = st.file_uploader(
    "Upload Audio for Ambient AI (MP3, WAV, M4A)", 
    type=['mp3', 'wav', 'm4a'],
    help="This module is currently in beta."
)

if audio_file:
    st.success(f"Audio loaded: {audio_file.name}")

st.markdown("---")

# --- Step 2: Medical Files Input ---
st.write("### 2. Patient History")
add_medical_file = st.radio(
    "Do you want to add a Medical file for this patient?", 
    ('No', 'Yes'),
    horizontal=True
)

uploaded_files = []

if add_medical_file == 'Yes':
    st.info("You can upload a single PDF or multiple image pages.")
    
    # This single uploader handles multiple files (acting as "Add Pages")
    uploaded_files = st.file_uploader(
        "Upload Patient Records (PDF or Images)", 
        type=['pdf', 'png', 'jpg', 'jpeg'], 
        accept_multiple_files=True
    )
    
    if uploaded_files:
        st.write(f"**{len(uploaded_files)} file(s) attached.**")
        for file in uploaded_files:
            st.caption(f"📄 {file.name}")

st.markdown("---")

# --- Step 3: Submission & Processing Simulation ---
if st.button("🚀 Submit & Generate Diagnosis", type="primary", use_container_width=False):
    
    # 1. Validation
    if not audio_file:
        st.warning("⚠️ Please upload an audio file to proceed.")
    else:
        # Create a container to hold the status updates
        status_container = st.status("Initializing AI System...", expanded=True)
        
        with status_container:
            # Simulate Audio Transcription
            st.write("🎙️ **Transcribing Audio...**")
            time.sleep(1.5) 
            st.write("✅ Transcription Complete.")
            
            # Simulate File Reading
            if add_medical_file == 'Yes' and uploaded_files:
                st.write("📂 **Reading Patient Files...**")
                time.sleep(1.5)
                st.write("✅ Medical History Extracted.")
            elif add_medical_file == 'Yes' and not uploaded_files:
                st.warning("⚠️ No medical files found, skipping history...")
            else:
                st.write("ℹ️ No medical files selected. Proceeding with audio only.")

            # Simulate Diagnosis Generation
            st.write("🧠 **Creating Diagnosis...**")
            time.sleep(1.5)
            
            status_container.update(label="Analysis Complete!", state="complete", expanded=False)

        # Show Final Success Message
        st.success("🎉 Diagnosis Generated Successfully!")
        
        # Placeholder Results
        st.markdown("### 📋 Assessment Summary")
        st.info("The AI is ready to display the full report.")

# --- Disclaimer Section ---
st.markdown("""
<div class="disclaimer-box">
    <strong>⚠️ DISCLAIMER: AI-Assisted Diagnosis</strong><br>
    This diagnosis is generated by Artificial Intelligence and is subject to potential inaccuracies and risks. 
    It is designed to function <strong>solely as a decision support tool</strong>. 
    It does not replace professional medical judgment. 
    All outputs must be verified by a qualified healthcare professional before any clinical action is taken.
</div>
""", unsafe_allow_html=True)
